import type { Dictionary } from "./types";

/** English content. Mirrors es.ts — keep both files in sync. */
const en: Dictionary = {
  meta: {
    title: "Integra Sinergia | Integrated business consulting in Costa Rica",
    titleTemplate: "%s | Integra Sinergia",
    description:
      "Consulting in ISO management systems, environmental management and sustainability, compliance, KPIs, AI automation and web design. An integrated solution for organizations in Costa Rica that want to grow.",
    keywords: [
      "business consulting Costa Rica",
      "environmental consulting",
      "environmental management",
      "sustainability",
      "management systems",
      "ISO 9001",
      "ISO 14001",
      "process improvement",
      "automation",
      "artificial intelligence",
      "web design Costa Rica",
      "web development",
    ],
    ogAlt: "Integra Sinergia — Grow with solid systems.",
  },
  pages: {
    solutions: {
      title: "Integrated business solutions",
      description: "ISO management systems, sustainability and environmental management, compliance, data, AI automation and web design. Six areas connected in one system.",
    },
    method: {
      title: "The CRECE method",
      description: "How we work: Understand, Redesign, Execute, Consolidate and Scale. A method to move forward with structure and leave lasting capabilities in your team.",
    },
    about: {
      title: "About us",
      description: "Integra Sinergia is a Costa Rican boutique firm for integrated business consulting, founded by chemical engineers Fabiola Sosa Duarte and María Celeste Amaya.",
    },
    contact: {
      title: "Contact",
      description: "Tell us what your organization needs. Reach us by form, WhatsApp or email and we'll help you identify what to solve first.",
    },
  },
  ui: {
    breadcrumbHome: "Home",
    viewSolution: "View solution",
    allSolutions: "All solutions",
    prev: "Previous",
    next: "Next",
    otherSolutions: "Other solutions",
    talkTitle: "Shall we talk about your case?",
    talkText: "Tell us about your situation and we'll suggest where to start.",
  },
  home: {
    solutionsKicker: "What we do",
    solutionsTitle: "Six areas. One system.",
    solutionsLead: "Choose where to start. Each area solves a specific problem and connects with the others.",
    explore: [
      {
        key: "method",
        kicker: "How we work",
        title: "The CRECE method",
        text: "Understand before proposing, implement alongside your team and leave lasting capabilities.",
        cta: "Discover the method",
      },
      {
        key: "about",
        kicker: "Who we are",
        title: "A boutique firm",
        text: "Engineering, management and technology, working directly with the people doing the work.",
        cta: "Meet the team",
      },
    ],
  },
  about: {
    kicker: "About",
    title: "A boutique firm that sees the whole system.",
    lead: "Integra Sinergia was created to solve, in a connected way, what is usually managed separately: processes, sustainability, compliance, data, technology and digital presence.",
  },
  common: {
    skip: "Skip to content",
    homeShort: "Home",
    homeLabel: "Integra Sinergia, go to home",
    language: "Language",
    switchTo: "Ver en español",
    switchToShort: "ES",
  },
  nav: {
    links: [
      { key: "solutions", label: "Solutions" },
      { key: "method", label: "Method" },
      { key: "web", label: "Web design" },
      { key: "about", label: "About" },
    ],
    cta: "Tell us what you need",
    open: "Open menu",
    close: "Close menu",
  },
  hero: {
    eyebrow: "Integrated business consulting · Costa Rica",
    titleBefore: "An",
    titleAccent: "integrated",
    titleAfter: "solution for organizations that want to grow.",
    lead: "We connect management, sustainability, compliance, data, automation and digital presence. We understand the whole problem and build the combination of solutions your organization actually needs.",
    ctaPrimary: "Tell us what you need",
    ctaSecondary: "Explore solutions",
    tagline: "Grow with solid systems.",
    diagramTitle: "Diagram: six solution areas connected around your organization",
    diagramCenter: "Your organization",
    scroll: "Scroll",
  },
  problem: {
    kicker: "Where it starts",
    title: "Business problems rarely come alone.",
    lead: "A pending permit often hides an undocumented process. A management system without metrics turns into paperwork. A website that doesn't generate leads is a cost. When each piece is solved separately, the underlying problem stays.",
    symptoms: [
      { area: "gestion", text: "Operations depend on a few people and processes aren't documented." },
      { area: "sostenibilidad", text: "There are environmental or ISO requirements to meet, and no clear place to start." },
      { area: "cumplimiento", text: "Permits, licenses and deadlines are handled at the last minute." },
      { area: "datos", text: "Decisions are made without reliable indicators." },
      { area: "automatizacion", text: "The team loses hours on repetitive tasks that could run on their own." },
      { area: "web", text: "The digital presence doesn't reflect the company or generate opportunities." },
    ],
    closing: "If you recognize more than one, you don't need more vendors. You need an integrated view.",
  },
  connected: {
    kicker: "Everything is connected",
    titleBefore: "One team that sees",
    titleAccent: "the whole system.",
    lead: "We don't sell isolated services. We look at how your processes, obligations, data and digital presence relate to each other, and design a roadmap where every improvement strengthens the rest.",
    fragmented: {
      title: "Fragmented approach",
      caption: "One vendor per problem. No one sees the whole.",
      items: ["Processes", "Environment", "Permits", "Reports", "Software", "Web"],
    },
    integrated: {
      title: "The Integra approach",
      caption: "One diagnosis, one roadmap, solutions that reinforce each other.",
      center: "Your organization",
    },
    principles: [
      {
        title: "Diagnosis before proposal",
        text: "First we understand what's happening. Then we recommend what to do, in what order and why.",
      },
      {
        title: "Solutions that connect",
        text: "A procedure feeds an indicator; the indicator feeds an automation; the automation frees time to grow.",
      },
      {
        title: "Technical rigor, close collaboration",
        text: "An engineering background and management experience, with the closeness of a boutique firm: you work directly with the people doing the work.",
      },
    ],
  },
  solutions: {
    kicker: "Solutions",
    title: "Six areas. One system.",
    lead: "Each area solves a specific problem. Together, they build an organization that is more structured, measurable and ready to grow.",
    labels: {
      problem: "The problem",
      outcome: "What you get",
      why: "How we approach it",
      connects: "Connects with",
    },
    areas: [
      {
        id: "gestion",
        description: "Process mapping and redesign, operating manuals and ISO 9001, 14001, 45001 and 50001 management systems for companies in Costa Rica. Audit and certification readiness.",
        name: "Management, processes & systems",
        label: "Management",
        short: "Clear processes and management systems people actually use.",
        problem:
          "Operations rely on the memory of a few people, processes change depending on who runs them, and every audit is stressful.",
        outcomes: [
          "Process mapping and redesign",
          "Operating manuals and procedures",
          "ISO 9001, 14001, 45001 and 50001 management systems",
          "Audit and certification readiness",
        ],
        why: "We design systems for your team's day-to-day work, not binders for the audit.",
        cta: "Organize my processes",
        connects: ["datos", "cumplimiento", "automatizacion"],
      },
      {
        id: "sostenibilidad",
        description: "Environmental consulting in Costa Rica: environmental and waste management plans, Ecological Blue Flag (PBAE), ISO 14001 and sustainability indicators.",
        name: "Sustainability & environmental management",
        label: "Sustainability",
        short: "Environmental management with real business impact.",
        problem:
          "Environmental demands keep growing —from authorities, clients and supply chains— and environmental management feels like one more cost or paperwork.",
        outcomes: [
          "Environmental and waste management plans",
          "Support for Costa Rica's Ecological Blue Flag Program (PBAE)",
          "Sustainability strategy and indicators",
          "ISO 14001 environmental management systems",
        ],
        why: "We connect environmental management with your processes and data, so it drives efficiency, not just compliance.",
        cta: "Strengthen my environmental management",
        connects: ["gestion", "cumplimiento", "datos"],
      },
      {
        id: "cumplimiento",
        description: "Support with procedures, health permits, business licenses, compliance audits and SICOP bid management for companies in Costa Rica.",
        name: "Compliance & administration",
        label: "Compliance",
        short: "Requirements up to date, without last-minute rushes.",
        problem:
          "Permits, business licenses, health requirements and public procurement processes take time and know-how the team doesn't always have.",
        outcomes: [
          "Support with procedures and health permits",
          "Business licenses and municipal requirements",
          "Compliance audits",
          "Bid preparation and management on SICOP",
        ],
        why: "We turn requirements into a controlled process, with owners, dates and evidence.",
        cta: "Get my requirements in order",
        connects: ["gestion", "sostenibilidad", "automatizacion"],
      },
      {
        id: "datos",
        description: "KPIs, tracking dashboards, root cause analysis and improvement plans to make decisions with reliable data.",
        name: "Data, KPIs & improvement",
        label: "Data",
        short: "Decisions based on what's really happening.",
        problem:
          "Data is spread across spreadsheets, emails and different systems, and no one has a clear view of performance.",
        outcomes: [
          "KPIs defined for each process",
          "Tracking dashboards",
          "Root cause analysis and improvement plans",
          "Management review routines",
        ],
        why: "We choose a few indicators that matter and connect them to concrete decisions.",
        cta: "Measure what matters",
        connects: ["gestion", "automatizacion", "web"],
      },
      {
        id: "automatizacion",
        description: "Process automation, tool integrations, automated reports and artificial intelligence assistants for companies in Costa Rica.",
        name: "Automation & artificial intelligence",
        label: "Automation",
        short: "Fewer repetitive tasks, more capacity.",
        problem:
          "The team spends hours copying data, chasing approvals, building reports and answering the same questions.",
        outcomes: [
          "Workflow and form automation",
          "Integrations between the tools you already use",
          "Reports that build themselves",
          "AI assistants grounded in your organization's information",
        ],
        why: "We automate processes we've organized first. Automating chaos only speeds it up.",
        cta: "Automate my operations",
        connects: ["datos", "gestion", "web"],
      },
      {
        id: "web",
        description: "Web design and development in Costa Rica: strategy, UX/UI, custom development, technical SEO and integrations with WhatsApp, CRM and automation.",
        name: "Web design & development",
        label: "Web",
        short: "A digital presence that works for your business.",
        problem:
          "The website is outdated, doesn't communicate the company's real value, or simply doesn't generate leads.",
        outcomes: [
          "Digital strategy and content architecture",
          "UX/UI design and custom development",
          "Technical SEO and analytics",
          "Integration with forms, WhatsApp, CRM and automations",
        ],
        why: "We design the website as part of your sales system: connected to your processes, data and goals.",
        cta: "Build my digital presence",
        connects: ["automatizacion", "datos", "gestion"],
      },
    ],
    unsure: {
      title: "Not sure where to start?",
      text: "That's the most common case. Tell us about your situation and we'll help you identify what to solve first.",
      cta: "Request a diagnosis",
    },
  },
  method: {
    kicker: "The CRECE method",
    title: "A method to move forward with structure.",
    lead: "Every project follows the same logic: understand before proposing, implement alongside your team, and leave lasting capabilities in place.",
    outputLabel: "Outcome",
    steps: [
      {
        letter: "C",
        name: "Comprender · Understand",
        text: "Diagnosis of the current situation: processes, requirements, data, tools and goals.",
        output: "Integrated diagnosis",
      },
      {
        letter: "R",
        name: "Rediseñar · Redesign",
        text: "We define the combination of solutions and the roadmap, with clear priorities.",
        output: "Prioritized roadmap",
      },
      {
        letter: "E",
        name: "Ejecutar · Execute",
        text: "We implement with your team: documentation, systems, tools and technology.",
        output: "Solutions up and running",
      },
      {
        letter: "C",
        name: "Consolidar · Consolidate",
        text: "Training, indicators and follow-up so what's implemented is sustained.",
        output: "Autonomous team and measurement",
      },
      {
        letter: "E",
        name: "Escalar · Scale",
        text: "With solid foundations, the organization is ready to grow, certify or automate further.",
        output: "Next stage of growth",
      },
    ],
    cta: "Start with a diagnosis",
  },
  web: {
    kicker: "Web design & development",
    titleBefore: "Your website is also part of",
    titleAccent: "your business system.",
    lead: "We don't build websites just to “be online”. We design the digital presence your company needs to communicate clearly, build trust and turn visits into opportunities, connected to your sales processes.",
    processTitle: "From business goal to production site",
    steps: [
      { name: "Strategy", text: "Goals, audience and value proposition." },
      { name: "UX/UI", text: "Architecture, journeys and prototypes." },
      { name: "Design", text: "Art direction aligned with your brand." },
      { name: "Development", text: "Custom code, fast and secure." },
      { name: "Integrations", text: "Forms, WhatsApp, CRM and automation." },
      { name: "SEO", text: "Technical foundation to rank in search." },
      { name: "Conversion", text: "Every section guides toward contact." },
      { name: "Growth", text: "Analytics and continuous improvement." },
    ],
    mockup: {
      url: "yourcompany.com",
      annotations: ["Clear message", "Technical SEO", "Call to action", "Connected form"],
    },
    deliverablesTitle: "What we build",
    deliverables: [
      { title: "Corporate websites", text: "Your company's main presence, designed to build trust." },
      { title: "Landing pages", text: "Pages focused on one service or campaign, built to convert." },
      { title: "Redesigns", text: "We renew existing sites without losing what already works." },
      { title: "Integrations", text: "We connect the site with your forms, WhatsApp, CRM and internal workflows." },
    ],
    proof: {
      title: "This website is our calling card.",
      text: "We designed and built it with the same process we use for our clients.",
      specs: ["Next.js + TypeScript", "Responsive design per device", "Technical SEO and structured data", "Bilingual ES / EN", "Optimized for speed"],
    },
    cta: "Get a website quote",
    secondary: "See all solutions",
  },
  automation: {
    kicker: "Automation & AI",
    title: "Down-to-earth artificial intelligence.",
    lead: "AI is useful when it solves a concrete problem. We start with the process, identify what's repetitive and connect it to the tools you already use.",
    flow: ["Organized process", "Connected data", "Automation", "Applied AI", "Time to grow"],
    principle: "Automating chaos only speeds it up. That's why we organize first.",
    examplesTitle: "Application examples",
    examples: [
      { title: "Deadlines under control", text: "Automatic alerts for permits, licenses, calibrations and audits." },
      { title: "Reports without copy-paste", text: "Indicators that update from your forms and spreadsheets." },
      { title: "Requests that sort themselves", text: "Forms that classify, assign and notify the right person." },
      { title: "Internal assistant", text: "An AI assistant that answers based on your procedures and documents." },
    ],
    cta: "Automate my operations",
  },
  sectors: {
    kicker: "Who it's for",
    title: "Built for growing organizations.",
    lead: "We work with companies that want to move from handling emergencies to building solid foundations.",
    items: [
      { name: "Growing SMEs", text: "That need structure to take the next step." },
      { name: "Industry & manufacturing", text: "With demanding processes, requirements and certifications." },
      { name: "Tourism & hospitality", text: "Where sustainability and service go hand in hand." },
      { name: "Food & agribusiness", text: "With strict health and environmental requirements." },
      { name: "Retail & services", text: "Looking for efficiency and a better digital presence." },
      { name: "Government suppliers", text: "That take part in public procurement through SICOP." },
    ],
  },
  team: {
    kicker: "Team",
    title: "The people behind Integra.",
    lead: "We're a boutique firm. When you work with Integra, you work directly with us.",
    focusLabel: "Focus areas",
    members: [
      {
        name: "Fabiola Sosa Duarte, Eng.",
        initials: "FS",
        credential: "Chemical Engineer",
        role: "Co-founder",
        bio: "Consultant in environmental management, management systems, sustainability and process improvement. She supports organizations implementing quality, environmental, safety and energy systems.",
        focus: ["Environmental management", "ISO systems", "Sustainability", "Process improvement"],
        photo: "",
        photoAlt: "Fabiola Sosa Duarte, co-founder of Integra Sinergia",
      },
      {
        name: "María Celeste Amaya, Eng.",
        initials: "MA",
        credential: "Chemical Engineer",
        role: "Co-founder",
        bio: "Consultant in business management and improvement, focused on technical solutions that organize operations and prepare them to grow.",
        focus: ["Business management", "Process improvement", "Technical solutions"],
        photo: "",
        photoAlt: "María Celeste Amaya, co-founder of Integra Sinergia",
      },
    ],
    portraitPending: "Photo coming soon",
  },
  projects: {
    kicker: "Projects",
    title: "Recent work.",
    lead: "A selection of projects where we connected several areas to solve a complete problem.",
    items: [],
  },
  finalCta: {
    title: "Not sure exactly what you need?",
    titleAccent: "That's the best time to talk.",
    lead: "Tell us what's happening in your organization. We'll help you identify what to solve first and how.",
    primary: "Tell us what you need",
    whatsapp: "Talk to Integra on WhatsApp",
  },
  contact: {
    kicker: "Contact",
    title: "Tell us what you need.",
    lead: "Write to us in your own words. You don't need a defined problem: that's what the diagnosis is for.",
    direct: {
      title: "Or reach us directly",
      whatsapp: "WhatsApp",
      email: "Email",
      phone: "Phone",
      location: "Location",
      locationValue: "Costa Rica",
    },
    form: {
      name: "Name",
      email: "Email",
      company: "Company or organization",
      phone: "Phone or WhatsApp",
      interest: "How can we help?",
      interestHint: "You can choose more than one.",
      unsure: "I'm not sure what I need",
      message: "Tell us about the situation",
      messagePlaceholder: "For example: we want ISO 9001 certification, but our processes aren't documented…",
      optional: "optional",
      required: "required",
      submit: "Send message",
      sending: "Sending…",
      successTitle: "Thank you, we received your message.",
      successText: "We'll review it and get back to you soon to talk about your situation.",
      error: "We couldn't send your message. Please try again or reach us on WhatsApp.",
      invalidEmail: "Please check the email format.",
      missing: "Please complete the required fields.",
      notConfigured: "The form isn't connected yet. In the meantime, reach us on WhatsApp or by email.",
      privacy: "We'll only use your information to reply to your inquiry.",
    },
  },
  whatsapp: {
    floating: "Talk to Integra",
    defaultMessage: "Hello, Integra Sinergia. I'd like to talk about what my organization needs.",
  },
  footer: {
    description: "Integrated business consulting: management, sustainability, compliance, data, automation and web design for organizations that want to grow.",
    solutionsTitle: "Solutions",
    companyTitle: "Integra",
    contactTitle: "Contact",
    companyLinks: [
      { key: "method", label: "CRECE method" },
      { key: "about", label: "About" },
      { key: "contact", label: "Contact" },
    ],
    rights: "All rights reserved.",
    builtBy: "Designed and built by Integra Sinergia.",
  },
  notFound: {
    title: "This page doesn't exist.",
    text: "The link may have changed. Let's go back home.",
    cta: "Go to home",
  },
};

export default en;
