import type { Dictionary } from "./types";

/** English content. Mirrors es.ts — keep both in sync. */
const en: Dictionary = {
  meta: {
    title: "Integra Sinergia | Business consulting in Costa Rica",
    titleTemplate: "%s | Integra Sinergia",
    description:
      "We integrate management, sustainability and technology so companies grow on solid systems. ISO systems, environmental management, automation and web design in Costa Rica.",
    keywords: [
      "business consulting Costa Rica",
      "environmental consulting",
      "environmental management",
      "sustainability",
      "management systems",
      "ISO 9001",
      "ISO 14001",
      "process improvement",
      "automation",
      "artificial intelligence",
      "web design Costa Rica",
      "web development",
    ],
  },
  pages: {
    solutions: {
      title: "Solutions",
      description:
        "Management, sustainability, technology and digital presence. We combine disciplines based on what each organization needs.",
    },
    projects: {
      title: "Projects",
      description: "Integra Sinergia projects: the problem, the solution and how the pieces came together.",
    },
    method: {
      title: "Method",
      description: "Understand, standardize, improve and scale. This is how we work with every organization.",
    },
    about: {
      title: "About",
      description:
        "Integra Sinergia is a Costa Rican boutique firm founded by chemical engineers Fabiola Sosa Duarte and María Celeste Amaya.",
    },
    contact: {
      title: "Let's talk",
      description: "Tell us where your company is and where it wants to go. We'll reply by email or WhatsApp.",
    },
  },
  common: {
    skip: "Skip to content",
    homeLabel: "Integra Sinergia, go to home",
    homeShort: "Home",
    switchTo: "Ver en español",
    switchToShort: "ES",
    menuOpen: "Open menu",
    menuClose: "Close menu",
  },
  nav: {
    links: [
      { key: "solutions", label: "Solutions" },
      { key: "projects", label: "Projects" },
      { key: "about", label: "About" },
    ],
    cta: "Let's talk",
  },
  ui: {
    home: "Home",
    viewAll: "View all",
    prev: "Previous",
    next: "Next",
    related: "Connects with",
    talkTitle: "Shall we talk about your case?",
    talkText: "Tell us your situation and we'll tell you where to start.",
  },
  hero: {
    title: "We make your company work better.",
    lead: "We integrate management, sustainability and technology so companies grow on solid systems.",
    ctaPrimary: "Tell us what you need",
    ctaSecondary: "Meet Integra",
  },
  manifesto: {
    title: "Your company is a system.",
    pieces: ["People", "Processes", "Information", "Technology", "Sustainability"],
    closing: "When the pieces work together, the business works better.",
  },
  pieces: {
    kicker: "Integrated solutions",
    title: "We connect the pieces.",
    lead: "We combine disciplines based on what each organization actually needs.",
    cta: "Explore solutions",
    pillars: [
      {
        id: "gestion",
        name: "Management",
        line: "Clear processes, compliance in order and ISO systems people use.",
        areas: ["gestion", "cumplimiento"],
      },
      {
        id: "sostenibilidad",
        name: "Sustainability",
        line: "Environmental management that also drives efficiency.",
        areas: ["sostenibilidad"],
      },
      {
        id: "tecnologia",
        name: "Technology",
        line: "Data to decide. Automation to move forward.",
        areas: ["datos", "automatizacion"],
      },
      {
        id: "digital",
        name: "Digital presence",
        line: "Websites that build trust and bring opportunities.",
        areas: ["web"],
      },
    ],
  },
  digital: {
    kicker: "Design & technology",
    title: "Your digital presence is part of your business too.",
    lead: "We design and build websites that represent your brand, build trust and turn visitors into opportunities.",
    cta: "See digital solutions",
    mockupAlt: "Integra Sinergia website on a computer screen",
    mobileAlt: "Integra Sinergia website on a phone",
  },
  automation: {
    lines: ["Less repetitive work.", "More time to grow the business."],
    lead: "Automation and artificial intelligence applied to real processes.",
    cta: "See automation & AI",
    examplesTitle: "Where it usually applies",
    examples: [
      { title: "Deadlines", text: "Alerts for permits, licenses, calibrations and audits." },
      { title: "Reports", text: "Indicators that update from your forms and spreadsheets." },
      { title: "Requests", text: "Forms that classify, assign and notify the right person." },
      { title: "Internal assistant", text: "Answers based on your procedures and documents." },
    ],
  },
  web: {
    processTitle: "How we do it",
    process: ["Strategy", "UX/UI", "Design", "Development", "Integrations", "SEO", "Conversion", "Growth"],
  },
  method: {
    kicker: "Method",
    title: "We have a method.",
    lead: "First we understand. Then we organize, improve and prepare the company to grow.",
    steps: [
      {
        name: "Understand",
        text: "We learn how your organization works today: processes, requirements, data and goals.",
        output: "Diagnosis and priorities",
      },
      {
        name: "Standardize",
        text: "We organize processes, owners and documents so work doesn't depend on memory.",
        output: "Clear, documented processes",
      },
      {
        name: "Improve",
        text: "We measure, correct and automate what makes sense.",
        output: "Indicators and improvements underway",
      },
      {
        name: "Scale",
        text: "We leave the foundation ready to grow, certify or expand.",
        output: "An organization ready to grow",
      },
    ],
    cta: "Discover our method",
    outputLabel: "Outcome",
  },
  solutions: {
    title: "We connect the pieces.",
    lead: "Every organization needs a different combination. These are the pieces we work with.",
    labels: { problem: "The problem", outcome: "What you get", why: "How we approach it" },
    areas: [
      {
        id: "gestion",
        name: "Management, processes & systems",
        short: "Clear processes and management systems people use.",
        description:
          "Process mapping and redesign, operating manuals and ISO 9001, 14001, 45001 and 50001 management systems in Costa Rica. Audit and certification readiness.",
        problem: "Operations depend on a few people and every audit is stressful.",
        outcomes: [
          "Process mapping and redesign",
          "Operating manuals and procedures",
          "ISO 9001, 14001, 45001 and 50001 management systems",
          "Audit and certification readiness",
        ],
        why: "We design systems for your team's daily work, not binders for the audit.",
        cta: "Organize my processes",
        related: ["datos", "cumplimiento", "automatizacion"],
      },
      {
        id: "sostenibilidad",
        name: "Sustainability & environmental management",
        short: "Environmental management with real business impact.",
        description:
          "Environmental consulting in Costa Rica: environmental and waste management plans, Ecological Blue Flag (PBAE), ISO 14001 and sustainability indicators.",
        problem: "Environmental demands keep growing and environmental management feels like paperwork.",
        outcomes: [
          "Environmental and waste management plans",
          "Support for the Ecological Blue Flag Program (PBAE)",
          "Sustainability strategy and indicators",
          "ISO 14001 environmental management systems",
        ],
        why: "We connect the environmental side with your processes and data, so it drives efficiency, not just compliance.",
        cta: "Strengthen my environmental management",
        related: ["gestion", "cumplimiento", "datos"],
      },
      {
        id: "cumplimiento",
        name: "Compliance & administration",
        short: "Requirements in order, without last-minute rushes.",
        description:
          "Procedures, health permits, business licenses, compliance audits and SICOP bid management for companies in Costa Rica.",
        problem: "Permits, licenses and public procurement take time and know-how the team doesn't always have.",
        outcomes: [
          "Procedures and health permits",
          "Business licenses and municipal requirements",
          "Compliance audits",
          "Bid preparation and management on SICOP",
        ],
        why: "We turn requirements into a controlled process, with owners, dates and evidence.",
        cta: "Get my requirements in order",
        related: ["gestion", "sostenibilidad", "automatizacion"],
      },
      {
        id: "datos",
        name: "Data, KPIs & improvement",
        short: "Decisions based on what's really happening.",
        description:
          "KPIs, tracking dashboards, root cause analysis and improvement plans to make decisions with reliable data.",
        problem: "Data is scattered across spreadsheets and emails, and no one sees the full picture.",
        outcomes: [
          "KPIs defined per process",
          "Tracking dashboards",
          "Root cause analysis and improvement plans",
          "Management review routines",
        ],
        why: "We choose a few indicators that matter and tie them to concrete decisions.",
        cta: "Measure what matters",
        related: ["gestion", "automatizacion", "web"],
      },
      {
        id: "automatizacion",
        name: "Automation & artificial intelligence",
        short: "Less repetitive work, more capacity.",
        description:
          "Process automation, tool integrations, automated reports and artificial intelligence assistants for companies in Costa Rica.",
        problem: "The team spends hours copying data, chasing approvals and building reports.",
        outcomes: [
          "Workflow and form automation",
          "Integrations between the tools you already use",
          "Reports that build themselves",
          "AI assistants grounded in your own information",
        ],
        why: "We automate processes we've organized first. Automating chaos only speeds it up.",
        cta: "Automate my operations",
        related: ["datos", "gestion", "web"],
      },
      {
        id: "web",
        name: "Web design & development",
        short: "A digital presence that works for your business.",
        description:
          "Web design and development in Costa Rica: strategy, UX/UI, custom development, technical SEO and integrations with WhatsApp, CRM and automation.",
        problem: "The website doesn't communicate the company's real value or doesn't generate leads.",
        outcomes: [
          "Digital strategy and content architecture",
          "UX/UI design and custom development",
          "Technical SEO and analytics",
          "Integration with forms, WhatsApp, CRM and automation",
        ],
        why: "We design the website as part of your sales system, not as a brochure.",
        cta: "Get a website quote",
        related: ["automatizacion", "datos", "gestion"],
      },
    ],
  },
  projects: {
    kicker: "Projects",
    title: "Selected work.",
    lead: "The problem, the solution and how the pieces came together.",
    labels: { problem: "Problem", solution: "Solution" },
    items: [
      {
        title: "Integra Sinergia",
        client: "In-house project",
        problem: "The brand had evolved and its digital presence didn't show it.",
        solution: "Strategy, design and development of a bilingual, fast website built to generate contact.",
        areas: ["web"],
        image: "/showcase/integra-desktop.jpg",
        imageAlt: "Integra Sinergia website home page",
      },
    ],
    cta: "See projects",
    upcoming: "New case studies in progress.",
  },
  team: {
    kicker: "Team",
    title: "Real people behind the solutions.",
    lead: "We combine engineering, management and strategic thinking to build solutions that work in real life.",
    members: [
      {
        name: "Fabiola Sosa Duarte, Eng.",
        initials: "FS",
        role: "Chemical Engineer · Co-founder",
        bio: "Environmental management, management systems, sustainability and process improvement.",
        photo: "",
        photoAlt: "Fabiola Sosa Duarte",
      },
      {
        name: "María Celeste Amaya, Eng.",
        initials: "MA",
        role: "Chemical Engineer · Co-founder",
        bio: "Business management and improvement, focused on technical solutions that bring order to operations.",
        photo: "",
        photoAlt: "María Celeste Amaya",
      },
    ],
    pending: "Photo coming soon",
  },
  about: {
    title: "A boutique firm that sees the whole system.",
    lead: "Integra Sinergia was created to solve, in a connected way, what is usually managed separately.",
    body: [
      "A company doesn't have a process problem, an environmental problem and a digital problem. It has a system that works better or worse.",
      "That's why we work directly with the people who make decisions, from diagnosis to implementation.",
    ],
  },
  finalCta: {
    title: "What does your company need?",
    lead: "Tell us where you are and where you want to go.",
    cta: "Talk to Integra",
  },
  contact: {
    kicker: "Let's talk",
    title: "Tell us what you need.",
    lead: "You don't need a defined problem. That's what the diagnosis is for.",
    direct: {
      title: "Or reach us directly",
      whatsapp: "WhatsApp",
      email: "Email",
      phone: "Phone",
      location: "Location",
      locationValue: "Costa Rica",
    },
    form: {
      name: "Name",
      email: "Email",
      company: "Company",
      phone: "Phone or WhatsApp",
      interest: "What would you like to talk about?",
      interestHint: "You can choose more than one.",
      unsure: "I'm not sure what I need",
      message: "Tell us about the situation",
      messagePlaceholder: "For example: we want ISO 9001 certification, but our processes aren't documented…",
      optional: "optional",
      submit: "Send",
      sending: "Sending…",
      successTitle: "Thank you. We received your message.",
      successText: "We'll write to you soon.",
      error: "We couldn't send your message. Please try again or reach us on WhatsApp.",
      invalidEmail: "Please check the email.",
      missing: "This field is required.",
      notConfigured: "The form isn't connected yet. Reach us on WhatsApp or by email.",
      privacy: "We only use your information to reply.",
    },
  },
  whatsapp: {
    label: "Talk to Integra",
    defaultMessage: "Hello, Integra Sinergia. I'd like to talk about what my company needs.",
  },
  footer: {
    line: "Grow with solid systems.",
    rights: "All rights reserved.",
  },
  notFound: {
    title: "This page doesn't exist.",
    text: "The link may have changed.",
    cta: "Back to home",
  },
};

export default en;
