import type { Dictionary } from "./types";

/**
 * Contenido en español (idioma principal).
 * Regla: nada de clientes, cifras, testimonios ni resultados inventados.
 * Los puntos marcados con TODO deben validarse antes del lanzamiento.
 */
const es: Dictionary = {
  meta: {
    title: "Integra Sinergia | Consultoría empresarial integral en Costa Rica",
    titleTemplate: "%s | Integra Sinergia",
    description:
      "Consultoría en sistemas de gestión ISO, gestión ambiental y sostenibilidad, cumplimiento, indicadores, automatización con IA y diseño web. Una solución integral para organizaciones en Costa Rica que quieren crecer.",
    keywords: [
      "consultoría empresarial Costa Rica",
      "consultoría ambiental",
      "gestión ambiental",
      "sostenibilidad",
      "PBAE",
      "sistemas de gestión",
      "ISO 9001",
      "ISO 14001",
      "ISO 45001",
      "mejora de procesos",
      "automatización",
      "inteligencia artificial",
      "diseño web Costa Rica",
      "desarrollo web",
    ],
    ogAlt: "Integra Sinergia — Crece con sistemas sólidos.",
  },
  common: {
    skip: "Saltar al contenido",
    homeLabel: "Integra Sinergia, ir al inicio",
    language: "Idioma",
    switchTo: "View in English",
    switchToShort: "EN",
  },
  nav: {
    links: [
      { href: "#soluciones", label: "Soluciones" },
      { href: "#metodologia", label: "Metodología" },
      { href: "#diseno-web", label: "Diseño web" },
      { href: "#automatizacion", label: "Automatización e IA" },
      { href: "#equipo", label: "Equipo" },
    ],
    cta: "Cuéntanos qué necesitas",
    open: "Abrir menú",
    close: "Cerrar menú",
  },
  hero: {
    eyebrow: "Consultoría empresarial integral · Costa Rica",
    titleBefore: "Una solución",
    titleAccent: "integral",
    titleAfter: "para organizaciones que quieren crecer.",
    lead: "Conectamos gestión, sostenibilidad, cumplimiento, datos, automatización y presencia digital. Entendemos el problema completo y construimos la combinación de soluciones que tu organización realmente necesita.",
    ctaPrimary: "Cuéntanos qué necesitas",
    ctaSecondary: "Explorar soluciones",
    tagline: "Crece con sistemas sólidos.",
    diagramTitle: "Diagrama: seis áreas de solución conectadas alrededor de tu organización",
    diagramCenter: "Tu organización",
    scroll: "Desliza",
  },
  problem: {
    kicker: "El punto de partida",
    title: "Los problemas de una empresa rara vez llegan solos.",
    lead: "Un permiso pendiente suele esconder un proceso sin documentar. Un sistema de gestión sin indicadores se convierte en papeleo. Un sitio web que no genera contactos es un gasto. Cuando cada parte se resuelve por separado, el problema de fondo sigue ahí.",
    symptoms: [
      { area: "gestion", text: "La operación depende de unas pocas personas y los procesos no están documentados." },
      { area: "sostenibilidad", text: "Hay requisitos ambientales o de una norma ISO que cumplir y no está claro por dónde empezar." },
      { area: "cumplimiento", text: "Permisos, patentes y vencimientos se resuelven a última hora." },
      { area: "datos", text: "Las decisiones se toman sin indicadores confiables." },
      { area: "automatizacion", text: "El equipo pierde horas en tareas repetitivas que podrían hacerse solas." },
      { area: "web", text: "La presencia digital no refleja lo que la empresa es ni genera oportunidades." },
    ],
    closing: "Si te reconoces en más de una, no necesitas más proveedores. Necesitas una visión integrada.",
  },
  connected: {
    kicker: "Todo está conectado",
    titleBefore: "Un solo equipo que ve",
    titleAccent: "el sistema completo.",
    lead: "No vendemos servicios aislados. Analizamos cómo se relacionan tus procesos, tus obligaciones, tus datos y tu presencia digital, y diseñamos una ruta donde cada mejora fortalece a las demás.",
    fragmented: {
      title: "Enfoque fragmentado",
      caption: "Un proveedor por problema. Nadie ve el conjunto.",
      items: ["Procesos", "Ambiente", "Trámites", "Reportes", "Software", "Web"],
    },
    integrated: {
      title: "Enfoque Integra",
      caption: "Un diagnóstico, una ruta, soluciones que se refuerzan.",
      center: "Tu organización",
    },
    principles: [
      {
        title: "Diagnóstico antes que propuesta",
        text: "Primero entendemos qué está pasando. Después recomendamos qué hacer, en qué orden y por qué.",
      },
      {
        title: "Soluciones que se conectan",
        text: "Un procedimiento alimenta un indicador; el indicador alimenta una automatización; la automatización libera tiempo para crecer.",
      },
      {
        title: "Rigor técnico, trato cercano",
        text: "Formación en ingeniería y experiencia en gestión, con la cercanía de una firma boutique: hablas directamente con quienes hacen el trabajo.",
      },
    ],
  },
  solutions: {
    kicker: "Soluciones",
    title: "Seis áreas. Un mismo sistema.",
    lead: "Cada área resuelve un problema concreto. Juntas, construyen una organización más ordenada, medible y preparada para crecer.",
    labels: {
      problem: "El problema",
      outcome: "Lo que obtienes",
      why: "Cómo lo abordamos",
      connects: "Se conecta con",
    },
    areas: [
      {
        id: "gestion",
        name: "Gestión, procesos y sistemas",
        label: "Gestión",
        short: "Procesos claros y sistemas de gestión que se usan.",
        problem:
          "La operación depende de la memoria de unas pocas personas, los procesos cambian según quién los haga y cada auditoría genera estrés.",
        outcomes: [
          "Mapeo y rediseño de procesos",
          "Manuales y procedimientos operativos",
          "Sistemas de gestión ISO 9001, 14001, 45001 y 50001",
          "Preparación para auditorías y certificación",
        ],
        why: "Diseñamos sistemas pensados para el día a día de tu equipo, no carpetas para la auditoría.",
        cta: "Ordenar mis procesos",
        connects: ["datos", "cumplimiento", "automatizacion"],
      },
      {
        id: "sostenibilidad",
        name: "Sostenibilidad y gestión ambiental",
        label: "Sostenibilidad",
        short: "Gestión ambiental con impacto real en el negocio.",
        problem:
          "Las exigencias ambientales crecen —de autoridades, clientes y cadenas de suministro— y la gestión ambiental se vive como un costo o un trámite más.",
        outcomes: [
          "Planes de gestión ambiental y de residuos",
          "Acompañamiento en el Programa Bandera Azul Ecológica (PBAE)",
          "Estrategia e indicadores de sostenibilidad",
          "Sistemas de gestión ambiental ISO 14001",
        ],
        why: "Conectamos la gestión ambiental con tus procesos y tus datos, para que genere eficiencia y no solo cumplimiento.",
        cta: "Fortalecer mi gestión ambiental",
        connects: ["gestion", "cumplimiento", "datos"],
      },
      {
        id: "cumplimiento",
        name: "Cumplimiento y gestión administrativa",
        label: "Cumplimiento",
        short: "Requisitos al día, sin carreras de último minuto.",
        problem:
          "Permisos, patentes, requisitos sanitarios y procesos de contratación pública consumen tiempo y conocimiento que el equipo no siempre tiene.",
        outcomes: [
          "Acompañamiento en trámites y permisos sanitarios",
          "Gestión de patentes y requisitos municipales",
          "Auditorías de cumplimiento",
          "Preparación y gestión de ofertas en SICOP",
        ],
        why: "Convertimos los requisitos en un proceso controlado, con responsables, fechas y evidencias.",
        cta: "Poner mis requisitos al día",
        connects: ["gestion", "sostenibilidad", "automatizacion"],
      },
      {
        id: "datos",
        name: "Datos, indicadores y mejora",
        label: "Datos",
        short: "Decisiones basadas en lo que realmente pasa.",
        problem:
          "Los datos están repartidos en hojas de cálculo, correos y sistemas distintos, y nadie tiene una visión clara del desempeño.",
        outcomes: [
          "Indicadores (KPI) definidos por proceso",
          "Tableros de seguimiento",
          "Análisis de causa raíz y planes de mejora",
          "Rutinas de revisión para la dirección",
        ],
        why: "Elegimos pocos indicadores que importan y los conectamos con decisiones concretas.",
        cta: "Medir lo que importa",
        connects: ["gestion", "automatizacion", "web"],
      },
      {
        id: "automatizacion",
        name: "Automatización e inteligencia artificial",
        label: "Automatización",
        short: "Menos tareas repetitivas, más capacidad.",
        problem:
          "El equipo dedica horas a copiar datos, perseguir aprobaciones, armar reportes y responder las mismas preguntas.",
        outcomes: [
          "Automatización de flujos y formularios",
          "Integraciones entre las herramientas que ya usas",
          "Reportes que se generan solos",
          "Asistentes de IA basados en la información de tu organización",
        ],
        why: "Automatizamos procesos que primero ordenamos. Automatizar el desorden solo lo acelera.",
        cta: "Automatizar mi operación",
        connects: ["datos", "gestion", "web"],
      },
      {
        id: "web",
        name: "Diseño y desarrollo web",
        label: "Web",
        short: "Una presencia digital que trabaja para tu negocio.",
        problem:
          "El sitio web está desactualizado, no comunica el valor real de la empresa o simplemente no genera contactos.",
        outcomes: [
          "Estrategia digital y arquitectura de contenidos",
          "Diseño UX/UI y desarrollo a medida",
          "SEO técnico y analítica",
          "Integración con formularios, WhatsApp, CRM y automatizaciones",
        ],
        why: "Diseñamos la web como parte de tu sistema comercial: conectada con tus procesos, tus datos y tus objetivos.",
        cta: "Crear mi presencia digital",
        connects: ["automatizacion", "datos", "gestion"],
      },
    ],
    unsure: {
      title: "¿No sabes por cuál empezar?",
      text: "Es lo más común. Cuéntanos la situación y te ayudamos a identificar qué resolver primero.",
      cta: "Solicitar diagnóstico",
    },
  },
  method: {
    kicker: "Metodología CRECE",
    title: "Un método para avanzar con orden.",
    lead: "Cada proyecto sigue la misma lógica: entender antes de proponer, implementar junto a tu equipo y dejar capacidades instaladas.",
    outputLabel: "Resultado",
    // TODO (Fabi): validar nombres y descripción de las etapas CRECE.
    steps: [
      {
        letter: "C",
        name: "Comprender",
        text: "Diagnóstico de la situación actual: procesos, requisitos, datos, herramientas y objetivos.",
        output: "Diagnóstico integral",
      },
      {
        letter: "R",
        name: "Rediseñar",
        text: "Definimos la combinación de soluciones y la ruta de trabajo, con prioridades claras.",
        output: "Hoja de ruta priorizada",
      },
      {
        letter: "E",
        name: "Ejecutar",
        text: "Implementamos con tu equipo: documentación, sistemas, herramientas y tecnología.",
        output: "Soluciones en funcionamiento",
      },
      {
        letter: "C",
        name: "Consolidar",
        text: "Capacitación, indicadores y seguimiento para que lo implementado se sostenga.",
        output: "Equipo autónomo y medición",
      },
      {
        letter: "E",
        name: "Escalar",
        text: "Con bases sólidas, la organización está lista para crecer, certificarse o automatizar más.",
        output: "Siguiente etapa de crecimiento",
      },
    ],
    cta: "Empezar por el diagnóstico",
  },
  web: {
    kicker: "Diseño y desarrollo web",
    titleBefore: "Tu página web también es parte de",
    titleAccent: "tu sistema empresarial.",
    lead: "No hacemos páginas para «estar en internet». Diseñamos la presencia digital que tu empresa necesita para comunicar con claridad, generar confianza y convertir visitas en oportunidades, conectada con tus procesos comerciales.",
    processTitle: "Del objetivo de negocio al sitio en producción",
    steps: [
      { name: "Estrategia", text: "Objetivos, audiencia y propuesta de valor." },
      { name: "UX/UI", text: "Arquitectura, recorridos y prototipos." },
      { name: "Diseño", text: "Dirección de arte alineada a tu marca." },
      { name: "Desarrollo", text: "Código a medida, rápido y seguro." },
      { name: "Integraciones", text: "Formularios, WhatsApp, CRM y automatización." },
      { name: "SEO", text: "Base técnica para aparecer en búsquedas." },
      { name: "Conversión", text: "Cada sección guía hacia el contacto." },
      { name: "Crecimiento", text: "Analítica y mejora continua." },
    ],
    mockup: {
      url: "tuempresa.cr",
      annotations: ["Mensaje claro", "SEO técnico", "Llamado a la acción", "Formulario conectado"],
    },
    deliverablesTitle: "Qué construimos",
    deliverables: [
      { title: "Sitios corporativos", text: "La presencia principal de tu empresa, diseñada para generar confianza." },
      { title: "Landing pages", text: "Páginas enfocadas en un servicio o campaña, pensadas para convertir." },
      { title: "Rediseño", text: "Renovamos sitios existentes sin perder lo que ya funciona." },
      { title: "Integraciones", text: "Conectamos la web con tus formularios, WhatsApp, CRM y flujos internos." },
    ],
    proof: {
      title: "Este sitio es nuestra carta de presentación.",
      text: "Lo diseñamos y desarrollamos con el mismo proceso que aplicamos para nuestros clientes.",
      specs: ["Next.js + TypeScript", "Diseño responsive por dispositivo", "SEO técnico y datos estructurados", "Bilingüe ES / EN", "Optimizado para velocidad"],
    },
    cta: "Cotizar mi sitio web",
    secondary: "Ver todas las soluciones",
  },
  automation: {
    kicker: "Automatización e IA",
    title: "Inteligencia artificial con los pies en la tierra.",
    lead: "La IA es útil cuando resuelve un problema concreto. Empezamos por el proceso, identificamos lo repetitivo y lo conectamos con las herramientas que ya usas.",
    flow: ["Proceso ordenado", "Datos conectados", "Automatización", "IA aplicada", "Tiempo para crecer"],
    principle: "Automatizar el desorden solo lo acelera. Por eso primero ordenamos.",
    examplesTitle: "Ejemplos de aplicación",
    examples: [
      {
        title: "Vencimientos bajo control",
        text: "Alertas automáticas para permisos, patentes, calibraciones y auditorías.",
      },
      {
        title: "Reportes sin copiar y pegar",
        text: "Indicadores que se actualizan a partir de tus formularios y hojas de cálculo.",
      },
      {
        title: "Solicitudes que se ordenan solas",
        text: "Formularios que clasifican, asignan y notifican al responsable correcto.",
      },
      {
        title: "Asistente interno",
        text: "Un asistente de IA que responde con base en tus procedimientos y documentos.",
      },
    ],
    cta: "Automatizar mi operación",
  },
  sectors: {
    kicker: "Para quién",
    title: "Pensado para organizaciones en crecimiento.",
    lead: "Trabajamos con empresas que quieren pasar de resolver urgencias a construir bases sólidas.",
    // TODO (Fabi): validar los sectores prioritarios.
    items: [
      { name: "Pymes en crecimiento", text: "Que necesitan orden para dar el siguiente paso." },
      { name: "Industria y manufactura", text: "Con procesos, requisitos y certificaciones exigentes." },
      { name: "Turismo y hospitalidad", text: "Donde sostenibilidad y servicio van de la mano." },
      { name: "Alimentos y agroindustria", text: "Con requisitos sanitarios y ambientales estrictos." },
      { name: "Comercio y servicios", text: "Que buscan eficiencia y una mejor presencia digital." },
      { name: "Proveedores del Estado", text: "Que participan en contratación pública mediante SICOP." },
    ],
  },
  team: {
    kicker: "Equipo",
    title: "Las personas detrás de Integra.",
    lead: "Somos una firma boutique. Cuando trabajas con Integra, trabajas directamente con nosotras.",
    focusLabel: "Áreas de enfoque",
    // TODO (Fabi): agregar fotografías profesionales en /public/team/ y validar biografías.
    members: [
      {
        name: "Ing. Fabiola Sosa Duarte",
        initials: "FS",
        credential: "Ingeniera Química",
        role: "Cofundadora",
        bio: "Consultora en gestión ambiental, sistemas de gestión, sostenibilidad y mejora de procesos. Acompaña a organizaciones en la implementación de sistemas de calidad, ambiente, seguridad y energía.",
        focus: ["Gestión ambiental", "Sistemas ISO", "Sostenibilidad", "Mejora de procesos"],
        photo: "",
        photoAlt: "Ing. Fabiola Sosa Duarte, cofundadora de Integra Sinergia",
      },
      {
        name: "Ing. María Celeste Amaya",
        initials: "MA",
        credential: "Ingeniera Química",
        role: "Cofundadora",
        bio: "Consultora en gestión y mejora empresarial, con enfoque en soluciones técnicas que ordenan la operación y la preparan para crecer.",
        focus: ["Gestión empresarial", "Mejora de procesos", "Soluciones técnicas"],
        photo: "",
        photoAlt: "Ing. María Celeste Amaya, cofundadora de Integra Sinergia",
      },
    ],
    portraitPending: "Fotografía próximamente",
  },
  projects: {
    kicker: "Proyectos",
    title: "Trabajo reciente.",
    lead: "Una selección de proyectos donde conectamos varias áreas para resolver un problema completo.",
    // La sección se muestra automáticamente cuando haya al menos un proyecto real autorizado.
    items: [],
  },
  finalCta: {
    title: "¿No sabes exactamente qué necesitas?",
    titleAccent: "Es el mejor momento para hablar.",
    lead: "Cuéntanos qué está pasando en tu organización. Te ayudamos a identificar qué resolver primero y cómo hacerlo.",
    primary: "Cuéntanos qué necesitas",
    whatsapp: "Hablar con Integra por WhatsApp",
  },
  contact: {
    kicker: "Contacto",
    title: "Cuéntanos qué necesitas.",
    lead: "Escríbenos con tus palabras. No necesitas tener el problema definido: para eso está el diagnóstico.",
    direct: {
      title: "O escríbenos directamente",
      whatsapp: "WhatsApp",
      email: "Correo",
      phone: "Teléfonos",
      location: "Ubicación",
      locationValue: "Costa Rica",
    },
    form: {
      name: "Nombre",
      email: "Correo electrónico",
      company: "Empresa u organización",
      phone: "Teléfono o WhatsApp",
      interest: "¿En qué podemos ayudarte?",
      interestHint: "Puedes elegir varias opciones.",
      unsure: "No estoy seguro de qué necesito",
      message: "Cuéntanos la situación",
      messagePlaceholder: "Por ejemplo: queremos certificarnos en ISO 9001, pero no tenemos procesos documentados…",
      optional: "opcional",
      required: "obligatorio",
      submit: "Enviar mensaje",
      sending: "Enviando…",
      successTitle: "Gracias, recibimos tu mensaje.",
      successText: "Lo revisaremos y te contactaremos pronto para conversar sobre tu situación.",
      error: "No pudimos enviar el mensaje. Inténtalo de nuevo o escríbenos por WhatsApp.",
      invalidEmail: "Revisa el formato del correo electrónico.",
      missing: "Completa los campos obligatorios.",
      notConfigured: "El formulario aún no está conectado. Mientras tanto, escríbenos por WhatsApp o correo.",
      privacy: "Usaremos tus datos únicamente para responder a tu consulta.",
    },
  },
  whatsapp: {
    floating: "Hablar con Integra",
    defaultMessage: "Hola, Integra Sinergia. Me gustaría conversar sobre lo que necesita mi organización.",
  },
  footer: {
    description: "Consultoría empresarial integral: gestión, sostenibilidad, cumplimiento, datos, automatización y diseño web para organizaciones que quieren crecer.",
    solutionsTitle: "Soluciones",
    companyTitle: "Integra",
    contactTitle: "Contacto",
    companyLinks: [
      { href: "#metodologia", label: "Metodología CRECE" },
      { href: "#equipo", label: "Equipo" },
      { href: "#contacto", label: "Contacto" },
    ],
    rights: "Todos los derechos reservados.",
    builtBy: "Diseñado y desarrollado por Integra Sinergia.",
  },
  notFound: {
    title: "Esta página no existe.",
    text: "Puede que el enlace haya cambiado. Volvamos al inicio.",
    cta: "Ir al inicio",
  },
};

export default es;
